# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2833112f2d61f9e1beab1ef80b5861d8a5836faf20f226e097146ba0a45fd22ac1397b30aa4beabfe3fd5499ba931fd7df65ac98b0481b18f175b1e5beff3f05

test:
  secret_key_base: 3ab6cb69df6e733390ebd7e0d52b9a019ff0c84ac3375530ebc60437743df7a9fc5b5ed63d73d3c117ad6f5f8842c06b9561b9be0bb19dc8458c0a4c3d13317c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
